### ISSUE TITLE
Suggestion: Include an option to open with TMUnlimiter for TMUF/TMNF Maps

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [ArkadySK/GbxMapBrowser#1]
Just a suggestion. If this is added, please let me know where it is!

**Comment by ArkadySK** [comment]
Hi, thanks for your idea!
I'll implement it soon.

**Comment by ENTPRESTIGIOUS** [comment]
> Hi, thanks for your idea! I'll implement it soon.

yay thanks!

**Comment by ArkadySK** [comment]
![obrázok](https://user-images.githubusercontent.com/74670743/150862814-93b7b327-284b-4713-b11a-72f86b768590.png)
I have implemented your feature in my build but somehow it seems that it doesn't work on that .exe

I will try to implement it in different way if possible

**Comment by ENTPRESTIGIOUS** [comment]
> ![obrázok](https://user-images.githubusercontent.com/74670743/150862814-93b7b327-284b-4713-b11a-72f86b768590.png) I have implemented your feature in my build but somehow it seems that it doesn't work on that .exe
> 
> I will try to implement it in different way if possible

I see...well uhh thanks for letting me know that you're working on it!

**Comment by ArkadySK** [comment]
Hi, I have finished the feature and it will be present in the next update. Thanks for your idea :D

**Comment by ArkadySK** [comment]
Hi, I have finished the feature and it will be present in the next update. Thanks for your idea :D

**Comment by ENTPRESTIGIOUS** [comment]
> Hi, I have finished the feature and it will be present in the next update. Thanks for your idea :D

oh boy great! Thanks!
