### ISSUE TITLE
Small suggestion: Option to save previous state of program

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [ArkadySK/GbxMapBrowser#2]
Hello again! Sorry but I have another small suggestion. Maybe have an option to open the program and continue at the directory that you were looking at including saving settings such as Sort By with Date Ascending instead of just having to do that every time you open the program.

**Comment by ArkadySK** [comment]
thanks for your idea, I am definitelly going to implement it :D

**Comment by ENTPRESTIGIOUS** [comment]
> thanks for your idea, I am definitelly going to implement it :D

yeah sorry for spamming issues 😅

**Comment by ArkadySK** [comment]
hi, I have finished implementation of the feature :D
